### ISSUE TITLE
At Prompt Translator Tab, why I hit "Translate" it auto overwrite the prompt in txt2img tab?

### ISSUE THREAD

**Issue by imppresser** [butaixianran/Stable-Diffusion-Webui-Prompt-Translator#4]
At Prompt Translator Tab, why I hit "Translate" it auto overwrite the prompt in txt2img tab? Then the "Send to ..." button seems pointless. I don't want the auto overwrite.

**Comment by butaixianran** [comment]
Hi, this is due to the problem of gradio. gradio is the ui library that SD webui used to create its whole UI.

And gradio is full of bugs and lack of many features. 

One big problem of gradio is, your webpage's javascript, can not communicate with python at server side. 

So, in txt2img tab, when you using the toolbar to translate prompt. Toolbar can not get the translated English text back.
Unless, python at server side always send translated English back to txt2img, no matter what.

This is the only way that top toolbar can work for now. And I believe most people won't go to extension tab, they just gonna translate prompt in txt2img tab, with that toolbar.

And even gradio offers a way to solve this in new version, SD webui won't update to it. The gradio version inside SD webui is old and full of bugs. But if they update it, there are a lot of changes need to be done, they seem don't want to re-write the UI again. 

So, maybe someday, I can find a hacking way to handle this, but before that, use the toolbar is the better choice.

**Comment by imppresser** [comment]
Thank you very much for your reply, which answered my doubts. As you said, toolbars cover most use cases. I use tab to translate some of the tags, which is some sorts of work of prompt engineering, and I originally thought it could work as a built-in translator. Because I didn't save the previous prompt content in time, overwriting the original prompt caused me some trouble. Knowing why will help me use this tool better, thanks.

**Comment by butaixianran** [comment]
ok, find a very hacking way to handle this. Update to the latest version, you won't have this problem anymore.
